[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ReflectX"
authors = [{name = "Logan Pearce", email = "lapearce@umich.edu"}]
dynamic = ["version", "description"]
